### ISSUE TITLE
Drag & Drop not working anymore on 1.7

### ISSUE THREAD

**Issue by Catarax** [unknownbrackets/maxcso#10]
The drag & drop feature  of an iso to maxco.exe doesn't work anymore since the 1.7 version.
Tried the same iso to 1.6 and the compression worked.

The iso didn't have french accents or whatever.

**Comment by unknownbrackets** [comment]
Oops, thanks for reporting.  Fixed in v1.7.2.  Was a bug in the Unicode handling, even for filenames without Unicode characters.

-[Unknown]

**Comment by Catarax** [comment]
Thanks!
Can you add also the 64bits build for v1.7.2 in releases section?

**Comment by unknownbrackets** [comment]
Ah, for some reason the upload failed.  I've reuploaded it.

-[Unknown]
