### ISSUE TITLE
How To Open Maxcso?

### ISSUE THREAD

**Issue by Rafidmuhaiminwafi** [unknownbrackets/maxcso#17]
I have just downloaded maxcso 1.1.0. It's just opening and immediately closing. I tried both 32bit and 64bit. So how to use it?

**Comment by RinMaru** [comment]
you drag your iso into it and it compresses it. if you want options  you need to open it in CMD

**Comment by unknownbrackets** [comment]
Yep.  To quote the README:

> **Basic usage**
>
>```sh
>maxcso myfile.iso
>```
>
>Or, drag the iso file into maxcso.exe on Windows.

If you're only using it with PPSSPP for PSP games, you could pass a couple options to get slightly better compression - but even without them you'll still get better compression than other CSO compressors.

-[Unknown]
