### ISSUE TITLE
Specify input/output folders for compression/decompression.

### ISSUE THREAD

**Issue by aorin1** [unknownbrackets/maxcso#20]
Can it be made?
I have something similar for CHDMAN.

@echo off 
@cls 
**set rompath=
set destpath=**
for /R "%rompath%" %%G in (*.cue) do ( 
echo. 
echo === Converting %%~nG to CHD ===
chdman createcd -i "%%G" -o "%destpath%\%%~nG.chd" -f 
echo. 
echo. 
)

**Comment by unknownbrackets** [comment]
If you're just looking for a batch file, this ought to work fine.  Put it in the same folder as maxcso.exe.

```cmd
@echo off

rem Put a full path here starting with drive letter (leave blank and it will ask.)
set inpath=
set outpath=
rem Put any extra args (like --fast or --block=32768) here.
set args=

if "%inpath%" == "" (
    set /p inpath="Input path (ISOs): "
)
if not exist "%inpath%" (
    echo Please create and populate this folder first: %inpath%
    exit /b 1
)

if "%outpath%" == "" (
    set /p outpath="Output path (CSOs): "
)
if not exist "%outpath%" (
    echo Please create this folder first: %outpath%
    exit /b 1
)

for /r "%inpath%" %%f in (*.iso) do (
    "%~dp0\maxcso.exe" %args% -o "%outpath%/%%~nf.cso" "%%f"
)
```

Basically the same concept.  This is what's nice about command line apps, you can automate things very easily.

-[Unknown]

**Comment by aorin1** [comment]
Amazing!
Can you specify a cso to iso batch as well?

**Comment by unknownbrackets** [comment]
Just change `*.iso` to `*.cso` and `.cso` below that to `.iso`, then change `set args=` to `set args=--decompress`.  Might also swap `ISOs` and `CSOs`.

-[Unknown]

**Comment by aorin1** [comment]
Thanks a lot, worked perfectly.
I'll spread the word, a lot of people will find the batch useful.
