### ISSUE TITLE
[Feature Request] Output directory

### ISSUE THREAD

**Issue by orbea** [unknownbrackets/maxcso#24]
Currently `maxcso` has `-o foo.cso` which allows to output the `input.iso` as a specific file name, but it can also be helpful if there also was `--output-prefix=string`.

This would allow the user to output all cso files to an output directory when converting files in a batch.
```
maxcso foo.iso bar.iso --output-prefix=/tmp/
```
Would result in `/tmp/foo.cso` and `/tmp/bar.cso` being created or it could be used when decompressing instead and would create iso files.

This option is also available in `flac(1)` and is documented in their man page.
```
--output-prefix=string
              Prefix each output file name with the given string.  This can be
              useful for encoding or decoding files to a different directory.
              Make sure if your string is a path name that it ends with a
              trailing `/' (slash).
```
Potentially `--output-prefix` could be a relative path too.

**Comment by orbea** [comment]
Also I should point out that `flac(1)` has `-o` too.
```
-o filename, --output-name=filename
              Force the output file name (usually flac just changes the
              extension).  May only be used when encoding a single file.  May
              not be used in conjunction with --output-prefix.
```

**Comment by unknownbrackets** [comment]
Would you expect that `maxcso foo/bar.iso --output-prefix=/tmp/` create `/tmp/foo/bar.cso` or `/tmp/bar.cso`?

In maxcso's case, it could make sense to specify both, because you can specify `-o foo.cso` multiple times (once per input file.)  In that case, I'd think the prefix would apply to each name, e.g. `maxcso --output-prefix=/home/ppsspp/umds/ /mnt/PSP_TYPE_A/UMD9660.ISO -o crisis_core.cso`.

-[Unknown]

**Comment by orbea** [comment]
I would expect `maxcso foo/bar.iso --output-prefix=/tmp/` to create `/tmp/bar.cso`. Until recently flac behaved differently and this caused problems for one of my scripts and for others when files can be read from the current directory, a full path or a relative path and `/tmp/foo/` may not exist where it would then fail to encode or decode flac files.  For reference see these links,

https://github.com/xiph/flac/pull/70
https://sourceforge.net/p/flac/bugs/463/
(It seems no one actually uses sourceforge to tell that guy his issue was fixed...)

I agree it could be nice to not have the same limitation as flac and be able to specify both.
