### ISSUE TITLE
Adding CSO support to HPSX64

### ISSUE THREAD

**Issue by Zero3K** [unknownbrackets/maxcso#28]
It would be nice if that were done for the PS2 emulator that is a part of it (and the PS1 emulator that is a part of it if possible). Its links are as follows:

Homepage: https://sourceforge.net/projects/hpsx64/
Source Code: https://github.com/Zero3K/hpsx64

**Comment by unknownbrackets** [comment]
Anyway, since this isn't really an issue in PPSSPP itself (more like an issue in hpsx64), I'm going to close it.

The code in maxcso to read / write CSOs is more complicated, because it uses multiple simultaneous threads for maximum throughput when decompressing / compressing.  I don't recommend using it as a model to implement CSO reading in an emulator.

-[Unknown]

**Comment by Zero3K** [comment]
How would I (or someone else) implement the code that you linked to?

**Comment by unknownbrackets** [comment]
It seems like `image` right now maps directly to a file (and there's cue sheet handling to determine where to read from.)  I'd suggest abstracting out the CSO logic to a separate class, and maybe have `image` be an interface (it might be most convenient for it to become a pointer.)

It seems like it would just need to support `Read(Async|Sync)`, `Create(Async|Sync)`, `Size`, and `WaitAsync` mainly.

This other class could then read the header on Create:
https://github.com/hrydgard/ppsspp/blob/ce6cb7e7c92643ab6e65928cc4cb114ac0d6df5f/Core/FileSystems/BlockDevices.cpp#L133-L207

And then essentially the code I linked to before on Read or the more efficient option for multiple sectors:
https://github.com/hrydgard/ppsspp/blob/ce6cb7e7c92643ab6e65928cc4cb114ac0d6df5f/Core/FileSystems/BlockDevices.cpp#L290-L381

Basically:
 * The CSO code should run whenever a sector would've been read from an ISO, e.g. when reading bytes `[X, X + 2048)` from the uncompressed data.
 * On init (one time per CSO file), it should load the index, which will map `X` to the actual compressed file position.
 * On read, you use the index to find the actual file position of the compressed data for `X` and read it in.
 * Then you simply deflate with zlib, which might be the most popular compression library there is.
 * Next you copy out the part of the compressed block you want (a compressed block may decompress to more than 2048 bytes.)
 * If you want more sectors, repeat this process for each `X`.
 * As an optimization, consider caching the last `X` and reusing the decompressed block.  More complex methods of caching often lose on overhead, but this cheap type of caching usually helps.

-[Unknown]

**Comment by Zero3K** [comment]
I have an issue with HPSX64 that I wrote more about at https://github.com/Zero3K/hpsx64/issues/1.

**Comment by Zero3K** [comment]
How do I contact the developer of HPSX64?

**Comment by Zero3K** [comment]
How would I add GZIP support to it?

**Comment by Zero3K** [comment]
No one else is interested in adding it.
