### ISSUE TITLE
Compilation under linux fix

### ISSUE THREAD

**Issue by PanKaczka** [unknownbrackets/maxcso#29]
Hi, this should be probably provided as a pulll-request, but I have some problems with it...
Nevertheless I was recently compiling your tool under linux and it seems that recent libuv (1.8) has changed its deployment.
Instead of uv/threadpool.h or uv/linux.h, uv-threadpool.h and uv-linux.h are used.

I've done following change for libuv/include/uv/unix.h:

 44 #include <signal.h>
 45 
 **46 #if defined(\_\_linux\_\_)
 47 #include "uv-threadpool.h"
 48 #else**
 49 #include "uv/threadpool.h"
 **50 #endif**
 51 
 52 #if defined(\_\_linux\_\_)
**53 # include "uv-linux.h"**
 54 #elif defined (\_\_MVS\_\_)

Would it be possible to integrate it in your code? :)

**Comment by unknownbrackets** [comment]
Sorry, I should probably better document version requirements.

The latest libuv uses uv/threadpool.h instead of uv-threadpool.h.  `maxcso` requires libuv v1.21.0 or higher, and has not been tested (on any platform) against the old version of libuv you're using.  I recommend updating libuv.

-[Unknown]

**Comment by PanKaczka** [comment]
Ok, thanks for this info. I'll update my libuv then :)
(Btw. in the meantime I've tested it with this legacy libuv, and everything seems to be working correctly)
We can close the issue.

**Comment by unknownbrackets** [comment]
If it works well (which isn't surprising, I do think older versions of maxcso were tested against an older libuv), I wouldn't be opposed to a `#if` based on UV_VERSION_HEX.

-[Unknown]
