### ISSUE TITLE
needs to support network path (or UNC path in Windows)

### ISSUE THREAD

**Issue by nayasis** [unknownbrackets/maxcso#44]
maxcso might not to support network path.

maxcso "\\NAS\ps2\test.iso"
-> Fail to compress (hang on few minutes and exit without error but there are no result)

maxcso "c:\test.iso"
-> success to compress

(I tested it on windows 10-64bit)

There are another ways to handle network file path ?

**Comment by unknownbrackets** [comment]
I'll fix this in a bit, looks like there's an issue in the glob handling.

As a workaround you can use `\\?\UNC\NAS\ps2\test.iso`, which should work fine.  As with other software, wildcards don't work with `\\?\...` paths, so you can't use `*.iso`.  It should work with regular network paths once I fix it.

-[Unknown]

**Comment by unknownbrackets** [comment]
Should be fixed in c176723.

-[Unknown]

**Comment by nayasis** [comment]
Thank you for fixing !

I compiled current release before you release. (windows binary)
[maxcso.zip](https://github.com/unknownbrackets/maxcso/files/6191680/maxcso.zip)

**Comment by unknownbrackets** [comment]
Here's the latest release:
https://github.com/unknownbrackets/maxcso/releases/tag/v1.13.0

Official releases are compiled with profile guided optimization, so they run faster (especially if you enable zopfli.)

-[Unknown]
