### ISSUE TITLE
Support MinGW-w64

### ISSUE THREAD

**Issue by KOLANICH** [unknownbrackets/maxcso#46]
This issue is mostly documenting the easiest way to build the projects in its current state on 64-bit Windows for usage on the same machine using MinGW-w64. The maintainer of this repo may want to integrate the stuff from this issue, but IMHO the right way is not to rely on makefiles, but use CMake.

To build using MinGW-w64 one needs:
* a proper version of MinGW-w64. I recommend using the ones with posix threading model, otherwise C++ 11 threads won't work.
* A cygwin-based environment with unix tools. You can use git-bash, which is a part of git distributions for Windows.
* You need to apply the following patch for Makefile. `-march=native` is for building on 64-bit machines for an own machine. It was the easiest way to make it compile for x86-64 without remembering the exact arg. It doesn't necessarily imply the best performance, I have done some kind of micro-researh, it has showed that sometimes the best performance is achieved when one compiles for an ancient CPUs of the same vendor.
* Also some small changes in the sources  are needed, the compiler will say you what to do in the error messages. 

```patch
diff --git a/Makefile b/Makefile
index 58ece5f..14d028a 100644
--- a/Makefile
+++ b/Makefile
@@ -5,20 +5,27 @@ MANDIR ?= $(PREFIX)/share/man
 CC ?= gcc
 CXX ?= g++
 
-CFLAGS ?= -O2
+CFLAGS ?= -march=native
 CXXFLAGS ?= $(CFLAGS)
 
 LIBS ?= libuv liblz4 zlib
 
-SRC_CFLAGS += -W -Wall -Wextra -Wno-implicit-function-declaration -DNDEBUG=1
-SRC_CXXFLAGS += -W -Wall -Wextra -std=c++11 -Izopfli/src -I7zip -DNDEBUG=1 \
-	-Ilibdeflate -Wno-unused-parameter -Wno-unused-variable -pthread \
-	`pkg-config --cflags $(LIBS)`
+SRC_CFLAGS += -W -Wall -Wextra -Wno-implicit-function-declaration -Ilibuv/include -Ilibuv/src -Ilibdeflate/lib -Ilibdeflate -Ilibdeflate/lib/x86 -DNDEBUG=1
+SRC_CXXFLAGS += -W -Wall -Wextra -std=c++11 -Izopfli/src -I7zip -Ilibuv/include -Ilz4/lib -DNDEBUG=1 \
+	-Ilibdeflate -Wno-unused-parameter -Wno-unused-variable -pthread
 
 SRC_CXX_SRC = $(wildcard src/*.cpp)
 SRC_CXX_OBJ = $(SRC_CXX_SRC:.cpp=.o)
 CLI_CXX_SRC = $(wildcard cli/*.cpp)
 CLI_CXX_OBJ = $(CLI_CXX_SRC:.cpp=.o)
+DFL_CC_SRC = $(wildcard libdeflate/lib/*.c libdeflate/lib/x86/*.c )
+DFL_CC_OBJ = $(DFL_CC_SRC:.c=.o)
+ZL_CC_SRC = $(wildcard zlib/*.c)
+ZL_CC_OBJ = $(ZL_CC_SRC:.c=.o)
+LZ4_CC_SRC = $(wildcard lz4/lib/*.c)
+LZ4_CC_OBJ = $(LZ4_CC_SRC:.c=.o)
+UV_CC_SRC = $(wildcard libuv/src/*.c libuv/src/win/*.c)
+UV_CC_OBJ = $(UV_CC_SRC:.c=.o)
 ZOPFLI_C_SRC = zopfli/src/zopfli/blocksplitter.c zopfli/src/zopfli/cache.c \
                zopfli/src/zopfli/deflate.c zopfli/src/zopfli/gzip_container.c \
                zopfli/src/zopfli/hash.c zopfli/src/zopfli/katajainen.c \
@@ -34,14 +41,14 @@ ZOPFLI_C_OBJ = $(ZOPFLI_C_SRC:.c=.o)
 	$(CC) -c $(SRC_CFLAGS) $(CFLAGS) -o $@ $<
 
 # TODO: Perhaps detect and use system libdeflate if available.
-maxcso: $(SRC_CXX_OBJ) $(CLI_CXX_OBJ) $(ZOPFLI_C_OBJ) 7zip/7zip.a libdeflate/libdeflate.a
-	$(CXX) -o $@ $(SRC_CXXFLAGS) $(CXXFLAGS) $^ `pkg-config --libs $(LIBS)`
+maxcso: $(SRC_CXX_OBJ) $(CLI_CXX_OBJ) $(ZOPFLI_C_OBJ) $(UV_CC_OBJ) $(DFL_CC_OBJ) $(ZL_CC_OBJ) $(LZ4_CC_OBJ) 7zip/7zip.a libdeflate/libdeflate.dll
+	$(CXX) -o $@ $(SRC_CXXFLAGS) $(CXXFLAGS) $^ -lwsock32 -lws2_32 -lwininet -lpsapi -liphlpapi -lUserEnv -luuid 
 
 7zip/7zip.a:
 	$(MAKE) -C 7zip 7zip.a
 
-libdeflate/libdeflate.a:
-	$(MAKE) -C libdeflate libdeflate.a
 
 install: all
 	mkdir -p $(DESTDIR)$(BINDIR)
```

**Comment by unknownbrackets** [comment]
I went ahead and fixed mingw support in 16d2a25.  Just use msys2 or something, similar procedure to building something like FFmpeg.  Install libraries via pacman, there's no need to compile libdeflate as a dll or similar.  Select your compiler using the shortcuts or using CC/CXX and keep -O2.

Of course, you can also use msys2 or just msvc.  I wouldn't expect better performance from mingw64.

-[Unknown]
