### ISSUE TITLE
Doesn't work with JPCSP emulator

### ISSUE THREAD

**Issue by MojoJojoDojo** [unknownbrackets/maxcso#55]
The README says that it should work under PSP and PS2 emulators without being specfiic but from what I saw it doesn't work under JPCSP even when you disable libdeflate so maybe it should be more clear or fixed.

**Comment by unknownbrackets** [comment]
Even with a 2048 block size?

It looks like JPCSP doesn't correctly handle other block sizes:
https://github.com/jpcsp/jpcsp/blob/cd47105372af2e4f270755328d753a40c3d39c80/src/jpcsp/filesystems/umdiso/CSOFileSectorDevice.java#L76

But that's really more of a JPCSP bug, I could change the README to indicate it's a known issue in JPCSP, though.  It already indicates ancient PPSSPP versions don't support it.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Yeah even with 2048 block size it seems.
It doesn't hang the emulator if you use that block size though.
I used `maxcso.exe --no-libdeflate --block=2048` btw.

**Comment by MojoJojoDojo** [comment]
Well I let them know of it and the developer seem to fix it https://github.com/jpcsp/jpcsp/commit/d32e126f7c174add9b268c4f932ad9ccf3f7568d
So closing it.
