### ISSUE TITLE
[Question] This will work on ExaGear Windows Emulator for android?

### ISSUE THREAD

**Issue by Gamemulatorer** [unknownbrackets/maxcso#59]
MaxCSO will work on ExaGear Windows Emulator?
![Screenshot_2021-12-20-08-18-26-419_com eltechs ed](https://user-images.githubusercontent.com/37603562/146696154-b743213a-8988-4523-86ba-841be9a517ce.jpg)

**Comment by unknownbrackets** [comment]
I don't know why it wouldn't.  Did you try it?

As far as I know, that's basically just WINE with x86 emulation.  I would expect it to support the APIs used, but haven't actually tried maxcso on WINE or similar.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> I don't know why it wouldn't. Did you try it?

Seriously I really don't know how to do it 😅✌️

But can you make .bat file to execute command just life this.

https://user-images.githubusercontent.com/37603562/146703322-c7c36a98-df85-4089-9ce8-bc4d6f78bea5.mp4

Sorry for being noob :(

**Comment by santigo049** [comment]
I recommend using it via [Termux](https://termux.com) , as you can compile maxcso from the source gaining better performance.

**Comment by unknownbrackets** [comment]
It is possible to compile maxcso on Android as a cli utility, just using cross compilation.

That said, if you want to try the emulator all you would need in the batch file is:

```bat
maxcso32 "Undead Knights (EUR).iso"
```

Also, if the emulator is any good and supports it, you could try dragging the iso file into maxcso32.exe.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Ok thanks I will try it.

**Comment by Gamemulatorer** [comment]
This is what happens :(
![Screenshot_2021-12-21-09-46-35-252_com eltechs ed](https://user-images.githubusercontent.com/37603562/146856912-7bd6f940-d777-4eec-b668-9cc99d3976c8.jpg)

**Comment by unknownbrackets** [comment]
That means it's working, but the terminal isn't handling the output correctly.  But it should still complete, it's just not an issue with ExaGear displaying the progress properly.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Thanks it's finally work!
From 393.56mb iso to 253.24mb cso 🎉
But it took 5-10minutes to finish 😅

Question is all cutscenes is still preserve? just compressed?

**Comment by unknownbrackets** [comment]
The time is probably due to emulation overhead, would run better compiled natively as santigo049 suggested.

But yes - it's lossless.  There are no changes to the data, it's just compressed (like a zip file is compressed.)  If you decompress it, you get exactly the original ISO.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Ok thanks ☺️
