### ISSUE TITLE
Doesn't seem to compress normal cd isos

### ISSUE THREAD

**Issue by i30817** [unknownbrackets/maxcso#6]
Trying in wine to compress with maxcso Phantasy Star Generation 1 and Phantasy Star Generation 2, which are remakes of the originals on the ps2. 
Apparently these were released on normal cds, not a dvds. PCSX2 plays the  isos.

Maxcso produces a 0 byte file on these files.

**Comment by unknownbrackets** [comment]
It doesn't spit out any error?  That's unusual.

What's the exact size of the source files?

-[Unknown]

**Comment by i30817** [comment]
PSG1 is 72,9 MB (72857904 bytes) (the fan translation)
PSG2 is 108,1 MB (108064992 bytes) (also the fan translation)

both isos

**Comment by unknownbrackets** [comment]
72857904 / 2048 = 35575.1484375
108064992 / 2048 = 52766.109375
72857904 /2048 = 30977
108064992 / 2352 = 45946

Only mode 1 discs are supported.  These are mode 2.  You should be getting an error ouputted to stderr.

As discussed in #3, mode 2 is not a power of two and isn't supported.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close this given the things mentioned in #3.

-[Unknown]
