### ISSUE TITLE
Psp go reboot

### ISSUE THREAD

**Issue by skelletR** [unknownbrackets/maxcso#60]
Hi, i have psp go firmware 6.60 PRO-C2 with your program make cso file smaller than Yacc program, but when run it on psp all good until pass 1 minute after just psp close itself (games play with cso with yacc program)

**Comment by unknownbrackets** [comment]
This is probably the same as #52.  If you disable `--no-libdeflate` does it work fine?  I'm still not really sure what libdeflate is doing that makes CFW crash...

The files will likely still be smaller than yacc.

-[Unknown]

**Comment by skelletR** [comment]
Yeah i make this file you say, maxcso-psp.cmd and drag and drop up in this, that seems works with at least 2 game I tried until now (Shrek The Third and Prince of Persia Rival Swords ).

**Comment by skelletR** [comment]
> This is probably the same as #52. If you disable `--no-libdeflate` does it work fine? I'm still not really sure what libdeflate is doing that makes CFW crash...
> 
> The files will likely still be smaller than yacc.
> 
> -[Unknown]

Yeah i make this file you say, maxcso-psp.cmd and drag and drop up in this, that seems works with at least 2 game I tried until now (Shrek The Third and Prince of Persia Rival Swords ).
