### ISSUE TITLE
Slight feature request: On the readme, include the commands needed to batch encode/decode a folder.

### ISSUE THREAD

**Issue by TomTurbine** [unknownbrackets/maxcso#63]
I believe many who enjoy this program would much appreciate you putting up how to make a file to batch encode.

I know command-line a little myself but don't remember loads of it and I am betting many know little to none as well who enjoy using your program as it does seem to offer the best compression for CSO as compared to the other compressors.

Including the commands needed to make such a file on your readme section would be much appreciated. Especially if you can specify an input and output folder.

Betting lots of people have asked here how to do it and searched online. Posting one of your readme would solve much of those questions and searching while having something that all the users know will work on the current version if anything ever changes with no having to question it.

Edit: From what I have read it would be:
for %%i in (*.iso) do maxcso "%%i" -o "%%~ni.cso"

But looking for that and trusting it for many would be rough and still doesn't address if they wanted them saved to a different directory.

**Comment by TomTurbine** [comment]
Someone made this for full use if you want to post it, supports input directory, output directory and arguments, saved it for myself and made another for decompression.

@echo off

rem Put a full path here starting with drive letter (leave blank and it will ask.)
set inpath=
set outpath=
rem Put any extra args (like --fast or --block=32768) here.
set args=

if "%inpath%" == "" (
    set /p inpath="Input path (ISOs): "
)
if not exist "%inpath%" (
    echo Please create and populate this folder first: %inpath%
    exit /b 1
)

if "%outpath%" == "" (
    set /p outpath="Output path (CSOs): "
)
if not exist "%outpath%" (
    echo Please create this folder first: %outpath%
    exit /b 1
)

for /r "%inpath%" %%f in (*.iso) do (
    "%~dp0\maxcso.exe" %args% -o "%outpath%/%%~nf.cso" "%%f"
)

**Comment by unknownbrackets** [comment]
I added some notes to the README and examples in the repo for reference.

-[Unknown]
