### ISSUE TITLE
Question How to make Adrenaline compatible csos?

### ISSUE THREAD

**Issue by RinMaru** [unknownbrackets/maxcso#77]
any time i compress a game with maxcso ill always have crashes in adrenaline is there a reason for this or is it a fault of adrenaline?

**Comment by unknownbrackets** [comment]
I suppose I need to get around to releasing a new version with this change: 161f99d81f81716943069387bb0234ce5a1355b3

It seems that PSP CFW (and probably Adrenaline) can't handle the output produced by `libdeflate` (I suspect maybe alignment or something.)  If you add `--no-libdeflate`, it should fix it in the latest release version.

-[Unknown]

**Comment by RinMaru** [comment]
Is there a drag n drop script? Im not good at cmd

**Comment by unknownbrackets** [comment]
You can use this (put it in the same folder as maxcso.exe):

```
@echo off

rem This is where maxcso is (usually don't need to change.)
set maxcso=%~dp0\maxcso.exe

if not exist "%maxcso%" (
	echo Could not find maxcso.exe
	exit /b 1
)

"%maxcso%" --no-libdeflate --block=2048 %*
pause
```

-[Unknown]

**Comment by RinMaru** [comment]
Thank you very much x3

**Comment by CookiePLMonster** [comment]
> I suppose I need to get around to releasing a new version with this change: [161f99d](https://github.com/unknownbrackets/maxcso/commit/161f99d81f81716943069387bb0234ce5a1355b3)

As somebody who just ran into the same issue and found this GH issue, yes please do.
