### ISSUE TITLE
Drag & Drop : CSO to ISO

### ISSUE THREAD

**Issue by Catarax** [unknownbrackets/maxcso#8]
**It would be cool if with a drag & drop of a cso to the exe, it decompress to iso with the internal command :**
`maxcso --decompress MY_CSO.cso -o MY_CSO.iso`

It would be better than doing it manually.
Thanks!

**Comment by unknownbrackets** [comment]
Well, this really isn't intended as a decompression program, it's intended as a compressor and even recompressor.

For example, I would argue that the more interesting thing for maxcso to do if you dragged a cso file into it might be to recompress the cso to a smaller cso file.  After all, maxcso performs better than most other cso compressors (both in speed and compression ratio), which is basically why maxcso was written in the first place.

That's what would happen if you ran the below, after all:

`maxcso my.cso -o new.cso`

In any case, I think there's at least one GUI frontend for maxcso floating around, which might have this functionality.  That provides a better way to give the user a choice.

Alternatively, if you really want something you can drag and drop into, you can create a "decompress.bat" like this:

```bat
@echo off

"%~dp0\maxcso.exe" --decompress "%1" -o "%~dpn1.iso"
```

You can drag files into that and it'll decompress as you requested.

-[Unknown]

**Comment by Catarax** [comment]
Many thanks for the details!

**Comment by BParks21** [comment]
> Well, this really isn't intended as a decompression program, it's intended as a compressor and even recompressor.
> 
> For example, I would argue that the more interesting thing for maxcso to do if you dragged a cso file into it might be to recompress the cso to a smaller cso file. After all, maxcso performs better than most other cso compressors (both in speed and compression ratio), which is basically why maxcso was written in the first place.
> 
> That's what would happen if you ran the below, after all:
> 
> `maxcso my.cso -o new.cso`
> 
> In any case, I think there's at least one GUI frontend for maxcso floating around, which might have this functionality. That provides a better way to give the user a choice.
> 
> Alternatively, if you really want something you can drag and drop into, you can create a "decompress.bat" like this:
> 
> ```batchfile
> @echo off
> 
> "%~dp0\maxcso.exe" --decompress "%1" -o "%~dpn1.iso"
> ```
> 
> You can drag files into that and it'll decompress as you requested.
> 
> -[Unknown]

Hi when I use this .bat with the command provided and drag multiple into the .bat it only decompresses the first .cso. How do I tell it to do it for all of them dragged into it?

**Comment by unknownbrackets** [comment]
As long as your files have .cso extensions, you can use:

```cmd
@echo off
""%~dp0\maxcso.exe" --decompress %*
```

-[Unknown]

**Comment by BParks21** [comment]
> As long as your files have .cso extensions, you can use:
> 
> ```batchfile
> @echo off
> 
> "%~dp0\maxcso.exe" --decompress %*
> ```
> 
> -[Unknown]

Thank you, really appreciate it!

**Comment by BParks21** [comment]
> As long as your files have .cso extensions, you can use:
> 
> ```batchfile
> @echo off
> 
> "%~dp0\maxcso.exe" --decompress %*
> ```
> 
> -[Unknown]

@unknownbrackets Yeah man idk, I made a .bat file with the command you provided and it doesn't work. I have my 2 games with .cso file extension that were converted from .iso in a folder with the .bat and maxcso.exe. Doesn't do anything. This bat file works perfectly though. 

@ECHO OFF
  maxcso --decompress *.cso
