### ISSUE TITLE
French accents support

### ISSUE THREAD

**Issue by Catarax** [unknownbrackets/maxcso#9]
If a game contains caracters like "é", maxcso will not be able to handle the file at all.
By the way, accent to the result file will be an interogative point (i have used the command line).

Example of what result from a decompression:
http://i.imgur.com/zkKho7y.png

**Comment by unknownbrackets** [comment]
Right, I'd forgotten to handle Unicode paths at all.  The file handling was all Unicode safe, just not the argument parsing.

1.7.0 should handle these filenames correctly.

-[Unknown]

**Comment by unknownbrackets** [comment]
Whoops, made a silly mistake, make sure you're using v1.7.1.

-[Unknown]
